### ISSUE TITLE
Dozens of hidden videos including 60% of the Chicken Defense playlist?

### ISSUE THREAD

**Issue by doug-w** [llamacademy/chicken-defense#1]
Hi!  Looking at https://www.youtube.com/watch?v=1wHXuPVJvDo&list=PLllNmP7eq6TRXItEcn9gEjZQkSTFVkvuE there's 2 public videos and 3 private videos, it looks like videos 1 and 4 are public, while 2, 3, 5 are hidden.  Across the channel it's similar, there's 153 public videos out of 220 total.  I don't see anything on patreon or youtube subscriptions that would limit the access to subscribers, am I missing something?

**Comment by llamacademy** [comment]
The videos on the playlist are unreleased. Apparently pre-scheduling them still shows them up on the playlist but as "private".
Wherever you pulled the total video count must include shorts because I don't have 220 non-shorts videos up yet :).

There is no pay-only videos or pay-only code on the channel though, it's all available for everyone. The Patreon/YouTube Membership/GitHub Sponsor is all opt-in to show support but does not get you exclusive secret videos or anything like that.

Edit: to make it more clear, I've removed the scheduled videos from the playlist so they won't show up until they're released
